---
apiVersion: v1
kind: Namespace
metadata:
  name: charles-rrsa
  labels:
    pod-identity.alibabacloud.com/injection: 'on'

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: account-charles
  namespace: charles-rrsa
  annotations:
    pod-identity.alibabacloud.com/role-name: k8s-role-charles
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: hellojava-deployment
  namespace: charles-rrsa
spec:
  selector:
    matchLabels:
      app: hellojava
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      namespace: charles-rrsa
      labels:
        app: hellojava
    spec:
      serviceAccountName: account-charles
      containers:
      - name: hellojava
        env:
        - name: HELLO-CONFIG-NKEY1
          valueFrom:
            configMapKeyRef:
              name: helloconfig
              key: nkey1
        - name: HELLO-SECRET-SKEY1
          valueFrom:
            secretKeyRef:
              name: hellosecret
              key: skey1
        image: ${IMAGE}
        ports:
        - containerPort: 80
        - containerPort: 8080
